services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: /home/yberrim/Inception-Project/srcs/requirements/nginx/
    networks:
      - inception
    ports:
      - 443:443
    env_file:
      - /home/yberrim/Inception-Project/srcs/.env
    volumes:
      - wp-volume:/var/www/html/wordpress
    restart: always

  mariadb:
    build:
      context: /home/yberrim/Inception-Project/srcs/requirements/mariadb/
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
      - /home/yberrim/Inception-Project/srcs/.env
    expose:
      - 3306
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    restart: always

  wordpress:
    build:
      context: /home/yberrim/Inception-Project/srcs/requirements/wordpress/
      dockerfile: Dockerfile
    env_file:
      - /home/yberrim/Inception-Project/srcs/.env
    container_name: wordpress
    expose:
      - 9000
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/html/wordpress

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/yberrim/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/yberrim/data/mariadb

networks:
  inception:
    driver: bridge
