version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: /home/yberrim/Desktop/Inception-Project/srcs/requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf
      - ./requirements/nginx/tools:/etc/nginx/tools
    restart: always
