version: '3'

services:
  nginx:
    build:
      context: /home/yberrim/project/srcs/requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/
    restart: always

  mariadb:
    build:
      context: /home/yberrim/project/srcs/requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
      - /home/yberrim/project/srcs/.env
    ports:
      - "3306:3306"
    networks:
      - inception
    restart: always

  wordpress:
    build:
      context: /home/yberrim/project/srcs/requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - /home/yberrim/project/srcs/.env
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
  inception:
    driver: bridge
