# version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: /home/yberrim/project/srcs/requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf
      - ./requirements/nginx/tools:/etc/nginx/tools
    restart: always
  mariadb:
    container_name: mariadb
    build: 
      context: /home/yberrim/project/srcs/requirements/mariadb/
      dockerfile: Dockerfile
