version: '3.7'

services:
  nginx:
    container_name: nginx
    build:
      context: /home/yberrim/project/srcs/requirements/nginx/
      dockerfile: Dockerfile
    env_file:
      - srcs/.env
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    restart: always
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build:
      context: /home/yberrim/project/srcs/requirements/mariadb/
      dockerfile: Dockerfile
    env_file:
      - srcs/.env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
  mariadb:
